(library
 (name mentat_context)
 (instrumentation
  (backend ppx_windtrap.coverage))
 (instrumentation
  (backend ppx_windtrap.mutate))
 (libraries
  eio
  eio.unix
  unix
  jsont
  frontmatter
  lpath
  mentat_prompts
  mentat_config
  mentat_digest
  mentat_llm
  mentat_tool
  mentat_diagnostic))
